### ISSUE TITLE
Improve/ease integration with third party build systems, e.g. CMake

### ISSUE THREAD

**Issue by Zingam** [microsoft/ProjectReunion#388] opened 2021-01-16 07:39 UTC
Please consider improving the integration of third party build system. Currently the most interesting combination is CMake/Ninja but that might change in the future, so a future proof approach should be considered.
This is more of a Visual Studio suggestion but I think it is highly relevant as a whole. Currently it is possible to build a CMake based UWP project but it is not possible to debug it.
I would like to be able to build/debug and test all sorts of CMake/Ninja C/C++ projects from Win32, UWP, WSL to Xbox right from Visual Studio without the need to generate .sln, etc.
Visual Studio has excellent CMake support but then CMake/Nuget/C++/MSBuild/vcpkg, etc. don't really work very well together as a whole yet.

**Comment by stevewri** [comment] 2021-01-18 20:08
Should this be consolidated with #74 ?

**Comment by Zingam** [comment] 2021-01-19 17:41
@stevewri Yes and No. As my code is cross-platform Windows/Apple/Google, etc. I really would like to have a complete, unified build/test and deploy experience based on CMake/Ninja preferably (at least until somebody comes up with a better build system).

**Comment by andrewleader** [comment] 2021-01-21 20:31
Thanks Zigam, we'll go ahead and close this as a dupe of #74, I've copied your feedback into your comment on that thread. Please do provide any additional info in that thread if you have any other additional requirements you think of!

**Closed by andrewleader** 2021-01-21 20:31 UTC
Labels: area-Developer tools, feature proposal
