### ISSUE TITLE
 int.Parse("") throws the exception

### ISSUE THREAD

**Issue by SenthilKumaranRajan** [microsoft/ProjectReunion#605] opened 2021-03-18 12:05 UTC
Using int.Parse("") leads to crash in project reunion and same works fine with WinUI3 Project templates

**Describe the bug**
unable to parse to int.  int.Parse("") throws the exception

**Steps to reproduce the bug**
1. Create the sample.
2. add the below code in the constructor.
int bytesCount = int.Parse("WINUI");
3. Run the sample. You can see application crashes.

**Expected behavior**
It works fine in WinUI3 Project templates

**Screenshots**

![image](https://user-images.githubusercontent.com/44424557/111623239-1bab5680-8810-11eb-8486-b1af2093402f.png)

**Version Info**
![image](https://user-images.githubusercontent.com/44424557/111623340-439aba00-8810-11eb-8449-1064732be681.png)

**Comment by riverar** [comment] 2021-03-18 17:05
What OS version? Please provide sample project.

**Comment by syncsiva** [comment] 2021-03-19 15:07
duplicate of https://github.com/microsoft/ProjectReunion/issues/599

**Comment by andrewleader** [comment] 2021-03-22 19:24
Closing this, we weren't able to repro the issue.

If you're still hitting this, please let us know what OS version you were hitting this on.

**Closed by andrewleader** 2021-03-22 19:24 UTC
Labels: needs-author-feedback, needs-triage :mag:
