### ISSUE TITLE
Allow Visual C++ projects that don't target UAP to reference WinMD files

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#499] opened 2021-03-01 06:22 UTC
Today Visual Studio doesn't allow to reference WinMD files using add reference dialog if that project doesn't target UAP

**Comment by andrewleader** [comment] 2021-03-01 21:16
Hi @Jaiganeshkumaran, this is great feedback but would be a request for Visual Studio itself to support. You can file a suggestion to the Visual Studio team here: https://developercommunity.visualstudio.com/report?entry=suggestion&space=8

Closing this issue. Thanks!

**Closed by andrewleader** 2021-03-01 21:16 UTC

**Comment by jonwis** [comment] 2021-03-01 21:32
IIRC, you can do this manually by editing the `vcxproj` file - the issue isn't specific to WinMDs or a hard block, it's that Visual Studio's _UX dialog_ doesn't let you cross the "universal" boundary; a Universal project can't reference a non-Universal target. The intent is to prevent someone from accidentally having their Universal project reference a non-Universal project containing artifacts which themselves use non-Universal-compliant APIs.  Those libs or DLLs would then either fail to link - because the VCRT runtimes were different - or they'd fail at runtime because the DLL expected to `CreateFile(...)` something that the UAP didn't have access to.

But you can manually edit the project references.
