### ISSUE TITLE
Bring back live tiles on Windows 10X

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#274] opened 2020-11-04 03:50 UTC
# Proposal: Bring back live tiles on Windows 10X

Live tiles are the best thing ever invented. Ever since they were introduced in 2012 on Windows desktop, apps were created to use Live tiles. Although the amount is not that huge, many people including me rely heavily on live tiles. On mobile devices like the Surface Neo, it makes more sense to have live tiles and innovate.

## Summary

Microsoft has decided to remove live tiles and replace it with static dumb old school icons to be consistent with other platforms. This is not acceptable and bad for the future of Windows. It doesn't need to be in the start screen but could be in the empty desktop space on 10x.

## Rationale

* Many existing apps use live tiles and they will be lost if live tiles aren't in 10x
* Windows will be unique in the OS space.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to use live tiles on 10X | Must |
| This proposal will allow end users to see live tiles on the start menu or the empty desktop | Must |

**Comment by mdtauk** [comment] 2020-11-04 04:06
I would like to see Live Tiles remain with Windows 10X.

With the addition of iOS Widgets to Apple's devices - that should be seen as a validation of the original concept.  Live Tiles should be invested in and further developed to make them more useful and added functionality and customisation.

Of course this brings to mind where they should exist in the UI.  I use a full screened Start Menu on my Surface Go and on my Desktop PC.  Most of the Live tiles are just icons, but some of them are Live and useful.  Finding a way for the Icons like with Windows 10X and the Live Tiles can co-exist should be investigated.

Then there are those that have wanted the Live Tiles to not be in the Start Menu / Launcher area, but pinned to the desktop.

Why can't they exist in both?  iOS uses icons that are contained in rounded square shapes, and extend that shape to encompass their widgets.  Now the 20H2 Start Menu does something similar, with Acrylic/Translucent tiles, where as Windows 10X has free floating icons of various shapes.  Maybe the two styles could co exist, with some kind of invisible grid, and rounded corners on the Live Tiles / Widgets you choose to Pin to the Desktop or Start/Launcher UIs will look more like cards, and so wont feel out of place on an invisible grid?

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 04:10
@mdtauk Something like this would be really great: https://www.youtube.com/watch?v=dGMEXtPRT_I

**Comment by mdtauk** [comment] 2020-11-04 04:14
> @mdtauk Something like this would be really great: https://www.youtube.com/watch?v=dGMEXtPRT_I

Bringing up Windows 8 era concepts wont be winning people around.  Android has had interactive widgets for a long time, but they are usually ugly and glitchy.  Apple's are quite similar to Microsoft's more restrictive Live Tiles, but has a bit more functionality compared to them.

Better to use more recent examples if you hope to persuade the teams of the **familiarity** and **cross-platform** appeal for keeping and refreshing them.

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 04:15
@mdtauk The static icons on 10x are just all apps list with no pin so they can co-exist.

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 04:16
@mdtauk Is this familiar? https://www.dummies.com/wp-content/uploads/79658.image2.jpg

**Comment by Neptune-mk2** [comment] 2020-11-04 04:18
I'm a big fan and user of tiles, I've used them since they became available in Windows 8, and continue to use them in my start screen in Windows 10, I have my current Start set up like a control center that brings me any relevant information I need at a glance, and I always thought the functionality of tiles could be improved by making them more like widgets as well! Seeing how Apple took a similar approach with their widgets, I think it would be great if Tiles are ever implemented in 10X that they could have additional widget like functionality.

Tiles not being in 10X has also been one of the things that has repulsed me from even considering 10X, I don't like the start interface 10X has at all, it feels like a dumbed down generic android home screen, and it doesn't bring the useful functionality tiles have in Windows 10, I couldn't have the same tile sections I have on my Sufrace where I have a whole section dedicated to being a news feed, some would argue you could get the same via notification but thats not a solution, that would just fill up my notification center with a bunch of articles and not give me a quick at a glance look at topics I pinned in start.

The lack of familiarity in 10X was also another big worry of mine, the start menu with tiles is more familiar and customization than a grid of static icons.

**Comment by mdtauk** [comment] 2020-11-04 04:22
> @mdtauk Is this familiar? https://www.dummies.com/wp-content/uploads/79658.image2.jpg
>
To old macOS "widgets" sure, but not to the new iOS ones.
![image](https://user-images.githubusercontent.com/7389110/98068751-d5eb8400-1e54-11eb-81ba-386742638145.png)

![image](https://user-images.githubusercontent.com/7389110/98068775-e7cd2700-1e54-11eb-9594-d42adaa82a6a.png)

![image](https://user-images.githubusercontent.com/7389110/98068795-fa476080-1e54-11eb-8172-ba59d88ae992.png)

![image](https://user-images.githubusercontent.com/7389110/98068821-15b26b80-1e55-11eb-8de6-bdfc99ce0a54.png)

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 07:00
Windows 10X has an empty desktop with no files so these could be put in there and the launcher menu could be the all apps screen.

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 07:29
Here's a concept on how it can look by me: 
![Windows-10X-scaled](https://user-images.githubusercontent.com/45227503/98081617-71a0e280-1e9d-11eb-86c8-836a7c3eb206.jpg)

**Comment by dragonDScript** [comment] 2020-11-04 15:35
I think that Microsoft should let non-packed Win32 Apps use Live Tiles. By use, I mean change the background color, size, etc. Because Tiles are limited for most people who use Win32.

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 15:37
@dragonDScript #172

**Comment by Jaiganeshkumaran** [comment] 2020-11-05 12:08
@dragonDScript Win32 apps can use live tiles as long as they are packaged.

**Comment by mdtauk** [comment] 2020-11-05 13:14
There may be some within Microsoft who think the name "Live Tiles" is a negative, so if needs be, they could be re-branded **App Cards**, which can live in the Start Menu, or on the Desktop.

**Comment by Jaiganeshkumaran** [comment] 2020-11-05 13:20
@mdtauk Not needed. Live tiles are not negative. Windows legacy users who hate change are to blame.

**Comment by dragonDScript** [comment] 2020-11-05 14:50
> @dragonDScript Win32 apps can use live tiles as long as they are packaged like regular UWP apps. I think all apps must become packaged one day to prevent slowing down and living junk behind and use MSIX as the installer. However, for other apps, I have already proposed that in #172.

What I meant is that unpacked win32 apps should be able to get custom live tiles. Because, as an example, Godot can't be installed per user or system. It is a portable .exe

**Comment by dragonDScript** [comment] 2020-11-05 14:51
> There may be some within Microsoft who think the name "Live Tiles" is a negative, so if needs be, they could be re-branded **App Cards**, which can live in the Start Menu, or on the Desktop.

This looks like a good idea. Live Tiles remembers to Windows 8 which wasn't very popular at all (even if I like it)

**Comment by Jaiganeshkumaran** [comment] 2020-11-05 15:12
Or how about the name Gadgets which was used in Vista and 7? It's familiar to lots of existing users.

**Comment by mdtauk** [comment] 2020-11-05 16:45
> Or how about the name Gadgets which was used in Vista and 7? It's familiar to lots of existing users.
>
You are sounding more and more troll like...  Gadgets are dead, let's not make Zombie UI lol

**Comment by dragonDScript** [comment] 2020-11-05 17:07
> Or how about the name Gadgets which was used in Vista and 7? It's familiar to lots of existing users.

Gadgets sound like unsecure (because they were lol). And slow (because of Vista). I would rename them to something different.

**Comment by stevewri** [comment] 2020-11-05 20:16
This is a shell design issue, not Reunion. I'll see if I can find the right owner.

**Comment by andrewleader** [comment] 2020-11-17 18:43
While this is partially a Shell design issue, **let's use this thread for developers to explain why they need Live Tiles/widgets for their users.** What scenarios are your users trying to accomplish in your apps? What do **you, as a developer, need** to deliver the best experience to your users?

**Comment by michael-hawker** [comment] 2020-11-20 22:11
I mean as a user, I find the action centered cluttered with notifications for messaging apps a lot. So, I either leave these all open running or pinned to my taskbar. If we had a richer live tile experience that was easy for devs/apps to use (back-end services as well), then for users that want to focus, they could pin tiles for these things and be able to glance at if they have any notifications and a quick peak at their most recent message and stuff.

I mean I still miss my (android) phone not easily just having my next calendar appointment shown by default on my lock screen... The stuff Windows Phone trail blazed still never lived up to it's full potential even today.

**Comment by lmcdougald** [comment] 2020-11-21 00:53
The biggest problem I have is that I didn't even know local live tile changes were an option. This feels like the type of thing where better messaging and UI in VS would have improved discovery and added value.

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 04:08
Notifications are good for apps that need to instantly show some info like messaging apps but for other apps it's distracting. Live tiles are a powerful concept and can be used for many things like background apps etc... However today it's very limited however just like what you did with notifications, why not allow some specific controls like buttons to be put up?

**Comment by mdtauk** [comment] 2020-11-21 07:52
> The biggest problem I have is that I didn't even know local live tile changes were an option. This feels like the type of thing where better messaging and UI in VS would have improved discovery and added value.

You obviously missed out on the Windows Phone and Windows 8 days :)

**Comment by lmcdougald** [comment] 2020-11-21 08:54
You misunderstand. I've always known that the live tile could use a web hook. I have no interest in writing a weather app or email client though so web hooks aren't very interesting to me. A local live tile change is much preferable.

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 09:34
Local live tile change is already possible @lmcdougald

**Comment by mdtauk** [comment] 2020-11-21 09:35
> You misunderstand. I've always known that the live tile could use a web hook. I have no interest in writing a weather app or email client though so web hooks aren't very interesting to me. A local live tile change is much preferable.

When Live Tiles were introduced, there was support for background tasks, and an API for local tile updates.

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 09:44
Making tiles more interactive is the way to go. Current tiles have reached the end of what it can support. You can imagine a browser downloading a file in the background and reporting the download progress on the tile if pinned. This will remove the need for taskbar progress (#68) since it can't show the actual information clearly. JumpList options could also be optionally provided removing the need for right-click. Many apps like screen recorders need to be accessed quickly and use a system tray icon. However, it feels cluttered because of over-use but if the tile is pinned on the Start screen, that could show quick options that will activate the app in the background or foreground. Apps like Word could for example show options directly enabling you to quickly open or create a file by passing arguments to the Word app without opening Word, then selecting an option. There can also be other uses for these kinds of tiles.

**Comment by mdtauk** [comment] 2020-11-21 09:46
> Making tiles more interactive is the way to go. Current tiles have reached the end of what it can support. You can imagine a browser downloading a file in the background and reporting the download progress on the tile if pinned. This will remove the need for taskbar progress (#68) since it can't show the actual information clearly. JumpList options could also be optionally provided removing the need for right-click. Many apps like screen recorders need to be accessed quickly and use a system tray icon. However, it feels cluttered because of over-use but if the tile is pinned on the Start screen, that could show quick options that will activate the app in the background or foreground. Apps like Word could for example show options directly enabling you to quickly open or create a file by passing arguments to the Word app without opening Word, then selecting an option. There can also be other uses for these kinds of tiles.

I don't think it should go so far as to be a mini app, but perhaps an actionable button when in Wide or Large formats?

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 09:48
@mdtauk  It's not going to provide the full capability also all options should open in the foreground app. For example, an app can replace system tray icons with a tile with options. Each option will simply activate the foreground app.

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 09:55
There should be a way to provide custom context menu items. For example, if you click on the news tile it will just open the app and currently, there's no way to get into the story. Although you could override that behaviour the intended action is to open the app. If the context menu had a "View story" option for the news tile, it will make it easier.

**Comment by mdtauk** [comment] 2020-11-21 09:57
> There should be a way to provide custom context menu items. For example, if you click on the news tile it will just open the app and currently, there's no way to get into the story. Although you could override that behaviour the intended action is to open the app. If the context menu had a "View story" option for the news tile, it will make it easier. JumpList could do this but it will appear in the all apps list as well as taskbar icon and not just the start menu.

There is, the Jump List.  These work on the Taskbar Icon as well as the App Tile

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 09:58
@mdtauk Right but then why apps are on the system tray with a custom context menu?

**Comment by mdtauk** [comment] 2020-11-21 09:59
> @mdtauk Right but then why apps are on the system tray with a custom context menu?

Windows 10X doesn't have a system tray.  And it is a more outdated way of doing an app.  These usually run in the background which UWP apps don't do.

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 10:01
Many UWP developers want the notification area icon (unofficially system tray) and today they are using a full trust component for that sometimes exclusively. Instead, if jumplists & tiles can offer a better experience, it will run everywhere. It's outdated and I don't like it but many developers want it.

**Comment by mdtauk** [comment] 2020-11-21 10:04
> Many UWP developers want the notification area icon (unofficially system tray) and today they are using a full trust component for that sometimes exclusively. Instead, if jumplists & tiles can offer a better experience, it will run everywhere. It's outdated and I don't like it but many developers want it.

Windows 10X is supposedly being pivoted to focus on a single screen experience, rather than launching first on Dual Screen devices.  Let's see if some affordance is made for background apps, without a task tray icon

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 10:07
Instead of just action buttons, there should be buttons like a list. For example, all your unread mails could be in a list and clicking inside the list view item border will open that message but clicking outside the list will open the app in default mode. Of course this for wide and large sizes. For regular size it will show as current with a static message that doesn't do anything. This list should have some border to open the app in default as well and must not have anything else like a context menu or other controls. It's purely system controlled and the app only loads text and images that are launched by the system with arguments.

**Comment by mdtauk** [comment] 2020-11-21 10:10
> Instead of just action buttons, there should be buttons like a list. For example, all your unread mails could be in a list and clicking inside the list view item border will open that message but clicking outside the list will open the app in default mode. Of course this for wide and large sizes. For regular size it will show as current with a static message that doesn't do anything. This list should have some border to open the app in default as well and must not have anything else like a context menu or other controls. It's purely system controlled and the app only loads text and images that are launched by the system with arguments.

You then enter problems with scrolling.  When using touch the tile would launch the app when you tap on it, but you also scroll with touching.

At the moment a Live Tile can cycle between items, and tapping it will take you to that content within the app.  So for larger tiles, a button you can tap or click is one thing - but displaying lists or multiple tap targets becomes a problem.

**Comment by Jaiganeshkumaran** [comment] 2020-11-21 10:14
The system should make sure that there's no scrolling so it only shows till the space is available. Even if you add more from a background task it should simply ignore it if it exceeds the space. Or the app could flip the tile and change the contents every second to a specified limit. The spacing should be large enough for touch and shouldn't be customizable. All this should only be available for wide and large sizes.

**Comment by Jaiganeshkumaran** [comment] 2020-11-26 06:56
https://aka.ms/AAaf10a

**Comment by Jaiganeshkumaran** [comment] 2020-12-27 09:00
I think Microsoft should get rid of tiles in the start menu and replace the desktop icons with tiles and the Start menu should be just an all apps list.

Put this on the desktop (without the hamburger menu):
![திரைப்பிடிப்பு (211)](https://user-images.githubusercontent.com/45227503/103167286-faaa1980-484f-11eb-8352-d365a119ddcf.png)

And make the start menu just like this: https://www.howtogeek.com/wp-content/uploads/2016/09/8ws_22.png

**Comment by Jaiganeshkumaran** [comment] 2020-12-27 09:05
Apps should run on top of tiles
![திரைப்பிடிப்பு (212)](https://user-images.githubusercontent.com/45227503/103167388-caaf4600-4850-11eb-94c6-bb04549c2dad.png)

**Comment by Jaiganeshkumaran** [comment] 2020-12-27 09:10
When Start is open
![68747470733a2f2f7777772e686f77746f6765656b2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30392f3877735f32322e706e67](https://user-images.githubusercontent.com/45227503/103167485-7062b500-4851-11eb-8910-f91065f1aeb9.png)

**Comment by Jaiganeshkumaran** [comment] 2020-12-27 09:11
The blur can be reduced to make it feel more like the actual desktop. Just replace icons with tiles on the desktop with multiple sections.

**Comment by Jaiganeshkumaran** [comment] 2020-12-27 09:25
I get it. Microsoft is afraid to change core parts since every time they change something a huge people refuse it and say pointless negative statements which don't make sense. However, Microsoft should be trying and not keep old stuff alive and new stuff dead. People will eventually get used to it.

**Comment by Jaiganeshkumaran** [comment] 2021-01-04 12:25
Maybe tiles and desktop icons could co-exist on the same desktop similar to the old Gadget feature and the Start menu can be simplified to just an all apps list

**Comment by michael-hawker** [comment] 2021-01-04 19:46
> Maybe tiles and desktop icons could co-exist on the same desktop similar to the old Gadget feature and the Start menu can be simplified to just an all apps list

Yeah, I don't know how I'd feel about forcing the start menu to replace the Desktop. Some folks just like a blank pretty picture. But I do like the idea of bringing back Gadgets, those were really useful. And part of that could just be a 'Start Menu' one which has the tiles for apps. It does make sense to provide a quick launch type of experience when you have nothing open.

Of course, you'd have to think about how this works with multi-mon as well.

**Comment by mdtauk** [comment] 2021-01-06 18:30
So Insider Build 21286 has dropped, and News/Weather has a new Taskbar Flyout, which brings up a bunch of "Live Tile" like cards.

![image](https://user-images.githubusercontent.com/7389110/103806429-ed114280-504c-11eb-9a52-2ee090b95e2f.png)

¬[image](https://46c4ts1tskv22sdav81j9c69-wpengine.netdna-ssl.com/wp-content/uploads/prod/sites/44/2021/01/News-and-interests-video.gif)

- Is this the future of Live Tiles for 10X?
- Will third parties be afforded this kind of Taskbar Flyout UI space to render their UI or Tiles?
- Will the user be able to create a _group_ on the Taskbar, which contains pinned tiles, where the Launcher/Start Menu has removed  Live Tiles?

**Comment by dragonDScript** [comment] 2021-01-06 20:16
This is enough for me. And will be well-received for most users (since it looks like ¡OS tiles).

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 01:53
> So Insider Build 21286 has dropped, and News/Weather has a new Taskbar Flyout, which brings up a bunch of "Live Tile" like cards.
> 
> ![image](https://user-images.githubusercontent.com/7389110/103806429-ed114280-504c-11eb-9a52-2ee090b95e2f.png)
> 
> ![image](https://camo.githubusercontent.com/abc90c9ee7dc3c78dcf6b430ce61545fb70af3023ba4937ac4f2308b270813e7/68747470733a2f2f3436633474733174736b7632327364617638316a396336392d7770656e67696e652e6e6574646e612d73736c2e636f6d2f77702d636f6e74656e742f75706c6f6164732f70726f642f73697465732f34342f323032312f30312f4e6577732d616e642d696e746572657374732d766964656f2e676966)
> 
> * Is this the future of Live Tiles for 10X?
> * Will third parties be afforded this kind of Taskbar Flyout UI space to render their UI or Tiles?
> * Will the user be able to create a _group_ on the Taskbar, which contains pinned tiles, where the Launcher/Start Menu has removed  Live Tiles?

I think it's a specific app implementation and a system-wide feature,

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 02:43
I don't get it, why would you have a flyout in the taskbar when you need to click to see when I can just open the app instead. Instead, it makes a lot more sense to keep on the desktop which is empty in Windows 10x. Also if a third-party app is supported it will get cluttered very fast. Instead, it should be on the desktop that can be placed anywhere

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 03:33
One major flaw with live tiles is that the primary tile is for launching the app and there's no way to get to the content. I use the News app a lot and opening it just opens the app instead of the story shown which is the intended way because it's a shortcut. The new flyout is much better since there are clickable item however it would be better to keep it on the desktop so you can see at without clicking the flyout.

**Comment by jonwis** [comment] 2021-01-07 08:37
> One major flaw with live tiles is that the primary tile is for launching the app

See the LaunchActivatedEventArgs.TileActivatedInfo.[RecentlyShownNotifications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Activation.TileActivatedInfo.RecentlyShownNotifications?view=winrt-19041) collection - on launch, the shell tells the app "here are the last N of your notifications that were shown."  The first item in the collection should be the notification that was visible when the user clicked the tile.

I'll check with the News app team to see what's going on there. Maybe we forgot to tell them when we added it.

**Comment by mdtauk** [comment] 2021-01-07 09:01
Secondary tiles were a thing, and I use them for specific mail inboxes.  The tiles need not only be a primary app launcher.

I'm happy with tiles on my full screen start menu, and if like to see tiles continue to exist and evolve with 10X

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 09:02
> Secondary tiles were a thing, and I use them for specific mail inboxes. The tiles need not only be a primary app launcher.
> 
> I'm happy with tiles on my full screen start menu, and if like to see tiles continue to exist and evolve with 10X
They are still a thing but a single widget could replace the need for secondary tiles.

**Comment by mdtauk** [comment] 2021-01-07 11:37
> > Secondary tiles were a thing, and I use them for specific mail inboxes. The tiles need not only be a primary app launcher.
> > I'm happy with tiles on my full screen start menu, and if like to see tiles continue to exist and evolve with 10X
> 
> They are still a thing but a single widget could replace the need for secondary tiles.

When you say widget, are you talking about a flyout with multiple Tiles?

I could have a single tile for my email app, but I prefer a tile for each grouped inbox.

**Comment by duke7553** [comment] 2021-01-10 20:56
As revolutionary as Live Tiles were when created last decade, they now deviate too much from the norm of most operating systems. 

We should instead strive for a high-quality widgets experience which does some of the heavy lifting with populating the widget with content for the developer automatically. For instance, Microsoft recognizes that many apps on users systems were PWAs installed from Edge rather than native programs. Currently, only native developers have the ability to use a background task to update their tiles' content. 

I'm proposing that the new experience is:
- **Easily usable by PWA and native developers:** Microsoft should work with the web community to draft a standard to add a new optional key to the PWA app manifest. Developers could supply rich widget content here from a URL
- **Intelligent:** Utilizes the Bing search indexer to scrape relevant engaging content for sites that provide nothing. It should be conservative about this and only find high-confidence branding assets
- **Static by default:** Avoids the un-orchestrated animations currently seen on Live Tiles in Start which distracts users just trying to find an app to open

**Comment by mdtauk** [comment] 2021-01-11 00:32
Moving to a more widget like system is fine, as long as they are surfaced alongside app icons, or in an easily accessible UI overlay.

The 10X Launcher only has App/Site Icons and recent document/sites/files accessed (similar to the WIndows 10 Timeline)

These Widgets should be closer to Live Tiles and iOS Widgets, than to the old Gadgets or Android style widgets.  Encourage a consistent design and style, and updatable either locally or via the cloud/web.

PWA support would also be good, and maybe include Adaptive Cards support.

Non live - App Tiles allowed App Icons to sit neatly in a Grid with the Live or resizable tiles.  But functionally they are the same as App Icons.  So if Live Tile/Widgets no longer live with the App Icons, then App Tiles are not needed, but wherever Widgets/Live Tiles will live - it needs to be as easy to access as Start is.

**Comment by Jaiganeshkumaran** [comment] 2021-01-11 02:56
More interactive widget-like tiles are fine however they should not put inside a flyout since that requires extra clicks to see one of them. Instead, they should be kept in the start menu or the desktop

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 04:38
Today most background apps use a notification area icon to provide quick access but if the tile itself is interactive and can show all options, it can replace the old era stuff

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 04:39
> > > Secondary tiles were a thing, and I use them for specific mail inboxes. The tiles need not only be a primary app launcher.
> > > I'm happy with tiles on my full screen start menu, and if like to see tiles continue to exist and evolve with 10X
> > 
> > 
> > They are still a thing but a single widget could replace the need for secondary tiles.
> 
> When you say widget, are you talking about a flyout with multiple Tiles?
> 
> I could have a single tile for my email app, but I prefer a tile for each grouped inbox.

Yes but an interactive tile could provide all in one.

**Comment by mdtauk** [comment] 2021-01-12 10:01
But I want my grouped inboxes separated, with a tile for each.  I don't want them all in one tile

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 10:02
> But I want my grouped inboxes separated, with a tile for each. I don't want them all in one tile

Maybe they can be grouped

**Comment by mdtauk** [comment] 2021-01-12 10:15
If there was support for widget flyouts, I could have my three grouped inboxes as tiles, and maybe add the calendar in there.

Another flyout could be just a group of media App icons with a Groove widget?

Lots of things become possible, if Windows allows third parties to make widgets and Live Tiles going into the future, and offers UI surfaces for these to live in.

10X has removed them from launcher, and if it doesn't want to add them back there, they could still support enhanced widget like Live Tiles and find a new place for them.

You've suggested the desktop, which is the lowest level of UI which goes beneath everything else and gets covered by windows.  On dual screened 10X devices, all apps run full screen.  So this is not an ideal place for them, which are designed for glancing at (and maybe simple interactions).

The launcher/Start Menu is the top most UI, and appears above everything else.

Any future UI surfaces for widgets and files, also needs to be top level, and can be brought into view no matter how many windows you have open or if both your dual screens have apps taking up those views.

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 10:16
Maybe a simple button in the taskbar that opens a screen full of tiles?

**Comment by mdtauk** [comment] 2021-01-12 10:27
10X has no system tray, so for the future of the feature, some kind of button will be needed.

Or you can make a "Widget Group" icon on the Launcher that pops out a flyout with widgets and tiles on.

This is a good reason this discussion exists, to show support for a feature we fear is being depricated, and try to find a way forward for supporting and enhancing this feature, whilst not preventing Microsoft from presenting the kind of UI it wants, and not bringing back Static App Tiles - where Microsoft wishes to present them as Icons.

The default can be Icons, and Widgets/Live Tiles can be added features for apps, if Microsoft gives us the UI surfaces to present them in.

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 10:30
That's a great idea but currently, the launcher isn't full width which needs to be fixed also I think widgets should be shown on the main screen and the all apps list as an expandable element.

**Comment by mdtauk** [comment] 2021-01-12 10:35
The launcher is near enough full width, it just chooses to render in a rounded border, but it is still on top of other UI.

On larger screens and on a desktop form factor, this will be like a normal Start Menu appearing above the start button, and won't be full screen.

I wonder how Tablet Mode will be supported.  I use my Start Menu full screen on desktop and on my Surface Go.  I got used to it with Windows 8, and I use lots of app tiles pinned

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 10:37
Why can't Microsoft make the desktop render on top?

**Comment by mdtauk** [comment] 2021-01-12 11:12
> Why can't Microsoft make the desktop render on top? I mean at least on desktop Windows, you can just press Windows + D or click the show desktop button

The desktop is what is beneath the windows you open.  If it were on top, you would not see anything other than your wallpaper lol

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 11:14
But widgets can be placed on the desktop even if it is behind all other windows. All you need to see them is press a button. Same can be done on Windows 10x.

**Comment by mdtauk** [comment] 2021-01-12 11:20
> But widgets can be placed on the desktop even if it is behind all other windows. All you need to see them is press a button. Same can be done on Windows 10x.

There could be a way to hide all you are working on to show the desktop.  It doesn't work so well on PC, and has a slow down affect minimising all the windows, and then bringing them back.

Bringing up the Start Menu/Start Screen is much smoother.  Also this Widget/Tile UI doesn't have to be full screen, it could overlay like the News and Interests UI does

![image](https://user-images.githubusercontent.com/7389110/104308168-27089b80-54c8-11eb-8664-3a5c27d201a9.png)

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 11:22
@mdtauk I think full screen is much better since you can see them all without that much scrolling.

**Comment by mdtauk** [comment] 2021-01-12 11:44
> @mdtauk I think full screen is much better since you can see them all without that much scrolling.

Sure, but if you only pin a few widgets, it doesn't have to be Full Screen.

Also you may want to group a few Live Tiles in different groups, so they can each have a small flyout.

Another thing with 10X at the moment.  You can not group App Icons into folders, and there is not way to arrange the Icons on a grid with spaces between them.  With my Start Screen I group design apps, office apps, games, and daily glance apps together.  A flat grid of App Icons doesn't allow this, and that I think is a regression too.

**Comment by Jaiganeshkumaran** [comment] 2021-01-12 11:46
> > @mdtauk I think full screen is much better since you can see them all without that much scrolling.
> 
> Sure, but if you only pin a few widgets, it doesn't have to be Full Screen.
Yes but the flyout can be resizable like the current desktop Start screen. Yes flyout can be down for grouping but not in the taskbar, instead the new tiles screen or flyout.

**Comment by shaheedmalik** [comment] 2021-01-27 11:04
The easiest thing to do is have the current 10x Launcher customizable.

Think of the various modes in File Manager
Icons
List
Details
Tiles

Now implement them in the Start Menu:
Live Tiles
Icons
List
Details

**Comment by Jaiganeshkumaran** [comment] 2021-01-28 12:35
I made a concept of interactive live tiles on the desktop. Instead of scrolling for overflow, I decided to make it paged similar to how Android handles the page. Since it's hard to swipe with a mouse, I have also included buttons for them. Existing desktop icons are inside a desktop tile as a list.

![Windows Reimagined - Desktop experience](https://user-images.githubusercontent.com/45227503/106139317-49223f00-6193-11eb-91c7-6fd2c4367035.png)

**Comment by andrewleader** [comment] 2021-01-28 20:52
This is an excellent discussion, how do folks feel about moving this discussion to GitHub Discussions in the Ideas section? I wanted to ask before moving this, but @Jaiganeshkumaran if you feel good with moving this to GitHub Discussions, let me know and I can migrate it (and all the comments and everything will move over there and be retained!).

**Comment by Jaiganeshkumaran** [comment] 2021-02-08 15:39
@andrewleader Ok go ahead

**Comment by andrewleader** [comment] 2021-02-08 16:50
Moving this discussion to GitHub Discussions into our Ideas section!

**Closed** 2021-02-08 16:50 UTC
Labels: area-Notifications, discussion, feature proposal, needs-triage :mag:
