### ISSUE TITLE
Crash while using enum

### ISSUE THREAD

**Issue by jeganraj-m** [microsoft/ProjectReunion#601] opened 2021-03-18 07:23 UTC
**Describe the bug**
Crash while using enum from custom control

**Steps to reproduce the bug**
1. Use below simple code to reproduce.
2. Declare dp property as enum.
3. Use the value in xaml.

Enum.cs

```
public enum Option
    {
        OptionA,
        OptionB
    }
```

CustomControl.cs

```
 public Option Option
        {
            get { return (Option)GetValue(OptionProperty); }
            set { SetValue(OptionProperty, value); }
        }

   public static readonly DependencyProperty OptionProperty =
    DependencyProperty.Register("Option", typeof(Option), typeof(CustomControl), new PropertyMetadata(Option.OptionA));

      string OptionValue;
      if (Option == Option.OptionA)
       {
              OptionValue = "Normal";
       }
       else if (Option == Option.OptionB)
       {
            OptionValue = "Simplified";
       }
```

 

MainPage.xaml

`<control:CustomControl  Option="OptionA"/>`

Refer: [Enum crash issue.zip](https://github.com/microsoft/ProjectReunion/files/6162205/Enum.crash.issue.zip)
**Expected behavior**
Enum value gets applied without any crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/74640452/111585888-01f51980-87e6-11eb-91df-d7bb57a0d9f8.png)

**Version Info**
 <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.2.12</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.ProjectReunion">
      <Version>0.5.0-prerelease</Version>
    </PackageReference>

**Additional context**
If we remove enum API there is no crash

`<control:CustomControl  />`

Refer: [Enum crash issue.zip](https://github.com/microsoft/ProjectReunion/files/6162205/Enum.crash.issue.zip)

**Comment by riverar** [comment] 2021-03-18 17:03
Dupe #599 same stack

**Comment by andrewleader** [comment] 2021-03-18 19:33
Closing as dupe of #599 (these are all related to resource loading issues on Windows 10 18363 and lower).

**Closed by andrewleader** 2021-03-18 19:33 UTC
Labels: needs-triage :mag:
