### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component when Windows.Storage.Pickers is using.

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/ProjectReunion#776] opened 2021-04-28 07:51 UTC
**Describe the bug**

When I'm trying to use `FileSavePicker` or `FileOpenPicker` from the Windows.Storage.Pickers namespace - get this error:
**Error HRESULT E_FAIL has been returned from a call to a COM component**

**Steps to reproduce the bug:**
1. Create an empty ProjectReunion solution
2. Try to call FilePicker window:
```CSharp
  FileSavePicker fileSavePicker = new FileSavePicker();
  var file = await fileSavePicker.PickSaveFileAsync();
```

**Screenshots**
![image](https://user-images.githubusercontent.com/50652041/116366519-0bbf6300-a80f-11eb-9c1f-449dfb769d56.png)
![image](https://user-images.githubusercontent.com/50652041/116366831-62c53800-a80f-11eb-9730-506721b45336.png)

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion 0.5.6

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :--------------------: |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by andrewleader** [comment] 2021-04-29 19:29
Hi @LeftTwixWand, thanks for reporting this.

This is a dupe of #466, you have to call an `InitializeWithWindow` API before calling the FilePicker from desktop MSIX apps (this is needed to link the APIs to your HWND, and is by-design and not a bug).

```csharp
 public sealed partial class MainWindow : Window
 {
      ...

        private async void myButton_Click(object sender, RoutedEventArgs e)
        {
            var filePicker = new FileOpenPicker();

            //Get the Window's HWND
            var hwnd = this.As<IWindowNative>().WindowHandle;

            //Make folder Picker work in Win32

            var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
            initializeWithWindow.Initialize(hwnd);
            filePicker.FileTypeFilter.Add("*");

            var folder = await filePicker.PickSingleFileAsync();
            myText.Text = folder != null ? folder.Path : string.Empty;
        }

        [ComImport]
        [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        public interface IInitializeWithWindow
        {
            void Initialize(IntPtr hwnd);
        }
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }
...
}
```

In the future, we could do some new feature work to eliminate this requirement and make the APIs work more straightforward (there's a pending ask for new file/folder picker APIs #88). But this pattern is required for a few Windows 10 APIs like secondary tiles. I'd suggest upvoting and commenting on #88 if you're interested in an improved API! Thanks!

**Closed by andrewleader** 2021-04-29 19:29 UTC
Labels: needs-triage :mag:

**Comment by LeftTwixWand** [comment] 2021-04-29 22:10
Thank You so much!

**Comment by docbrown** [comment] 2021-06-08 21:17
In the latest Project Reunion 0.5 release, I still get the `E_FAIL` error from `PickSingleFileAsync` after calling `IInitializeWithWindow::Initialize`.

**Comment by cody3b** [comment] 2023-03-06 17:41
> Hi @LeftTwixWand, thanks for reporting this.
> 
> This is a dupe of #466, you have to call an `InitializeWithWindow` API before calling the FilePicker from desktop MSIX apps (this is needed to link the APIs to your HWND, and is by-design and not a bug).
> 
> ```cs
>  public sealed partial class MainWindow : Window
>  {
>       ...
> 
>         private async void myButton_Click(object sender, RoutedEventArgs e)
>         {
>             var filePicker = new FileOpenPicker();
> 
>             //Get the Window's HWND
>             var hwnd = this.As<IWindowNative>().WindowHandle;
> 
>             //Make folder Picker work in Win32
> 
>             var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
>             initializeWithWindow.Initialize(hwnd);
>             filePicker.FileTypeFilter.Add("*");
> 
>             var folder = await filePicker.PickSingleFileAsync();
>             myText.Text = folder != null ? folder.Path : string.Empty;
>         }
> 
>         [ComImport]
>         [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
>         [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
>         public interface IInitializeWithWindow
>         {
>             void Initialize(IntPtr hwnd);
>         }
>         [ComImport]
>         [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
>         [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
>         internal interface IWindowNative
>         {
>             IntPtr WindowHandle { get; }
>         }
> ...
> }
> ```
> 
> In the future, we could do some new feature work to eliminate this requirement and make the APIs work more straightforward (there's a pending ask for new file/folder picker APIs #88). But this pattern is required for a few Windows 10 APIs like secondary tiles. I'd suggest upvoting and commenting on #88 if you're interested in an improved API! Thanks!

This solution works for me with FileOpenPicker, but does not work with FileSavePicker. I've tested this with Win UI 3 + .NET 5, 6, and 7 + last 10sih versions of WASDK.
