### ISSUE TITLE
Crash occurs while occurs ToString, Convert.ToString() function

### ISSUE THREAD

**Issue by VigneshRameshh** [microsoft/ProjectReunion#606] opened 2021-03-18 12:16 UTC
**Describe the bug**
Crash occurs while using ToString, Convert.ToString(). Please refer the below code examples:

public MainPage()
{
this.InitializeComponent();

double testDouble = 10;
string testString = testDouble.ToString();
}

**Steps to reproduce the bug**
1. Just run the sample

**Expected behavior**
The value should be converted correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/43605205/111624011-25818980-8811-11eb-93c9-9ffd398cdc55.png)

**Version Info**
![image](https://user-images.githubusercontent.com/43605205/111624162-5661be80-8811-11eb-9d8d-3f8abbee997c.png)

![image](https://user-images.githubusercontent.com/43605205/111624297-827d3f80-8811-11eb-9b07-c32aff1aaf71.png)

NuGet package version: 
![image](https://user-images.githubusercontent.com/43605205/111624141-4fd34700-8811-11eb-97ce-90a0afb25a97.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

Sample 
[App2.zip](https://github.com/microsoft/ProjectReunion/files/6163919/App2.zip)

**Comment by riverar** [comment] 2021-03-18 17:08
Dupe of #599, same stack.

**Comment by andrewleader** [comment] 2021-03-18 19:26
Closing as dupe of #599 (these are all related to resource loading issues on Windows 10 18363 and lower).

**Closed by andrewleader** 2021-03-18 19:26 UTC
Labels: needs-triage :mag:
