### ISSUE TITLE
Warnings after compiling Blank App (WinUI 3 in Desktop) in Visual Studio 2019 Version 16.10

### ISSUE THREAD

**Issue by sibille** [microsoft/ProjectReunion#863] opened 2021-05-26 15:02 UTC
**Describe the bug**
Warnings after compiling Blank App (WinUI 3 in Desktop) in Visual Studio 2019 Version 16.10

**Steps to reproduce the bug**
1. Create a new Blank App (WinUI 3 in Desktop) with Project Reunion VSIX 0.5.7
2. Build the project
=> 2 warnings related to code supported only on Windows show in the Error List

**Expected behavior**
No warnings should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/24698018/119682876-8649c580-be43-11eb-8d27-25311f6e537c.png)
Clicking on the warnings makes them disappear, but after re-building the warnings re-appear.
Adding more (Windows-specific) code increases the number of warnings.

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion 0.5.7

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
Started to see this after updating to Visual Studio 2019 Version 16.10

**Comment by andrewleader** [comment] 2021-05-27 19:02
I confirmed I'm seeing these warnings too. Thanks for reporting this, we'll get someone to look at it!

**Comment by RealTommyKlein** [comment] 2021-05-27 22:49
Thanks for the report - this looks like dotnet/sdk#17890 .  Will follow up with them there - in the meantime, it's safe to disable this warning in your project by adding something like this to your `.csproj`:

```
    <!-- Workaround for https://github.com/dotnet/sdk/issues/17890 -->
    <PropertyGroup>
      <NoWarn>CA1416, $(NoWarn)</NoWarn>
    </PropertyGroup>
```

**Comment by Scottj1s** [comment] 2021-05-28 16:20
Thanks @RealTommyKlein - closing this issue as it's being tracked by https://github.com/dotnet/sdk/issues/17890 and has a workaround

**Closed by Scottj1s** 2021-05-28 16:20 UTC
Labels: area-Developer tools, bug, needs-triage :mag:
