### ISSUE TITLE
AnyCPU Class Libraries no longer supported

### ISSUE THREAD

**Issue by dotMorten** [microsoft/ProjectReunion#939] opened 2021-06-17 22:02 UTC
**Describe the bug**
Since 0.8.0-preview (and RC as well), we're blocked from building .NET class libraries, because the AnyCPU check is not only applied to applications, but also against class libraries.
Class libraries has no problem being Any CPU - this limitation should not be enforced here, as this is a runtime limitation, not a compile time limitation.

**Steps to reproduce the bug**
1. Create the following project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-rc" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-rc" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-rc" />
  </ItemGroup>

</Project>
```
2. Compile
3. Observe the following error:
> Error		This version of WinUI does not support AnyCPU. Either set Platform or PlatformTarget to one of the following: x86, x64, or arm64.	MyClassLib	C:\Users\mn\.nuget\packages\microsoft.projectreunion.winui\0.8.0-rc\buildTransitive\Microsoft.WinUI.targets	15	

This is the culprit in that targets file:
```xml
<Target Name="ValidateWinUIPlatform"
          Condition="'$(_WinUIPlatformTarget)' == 'ARM' or '$(_WinUIPlatformTarget)'=='AnyCPU'"
          BeforeTargets="PrepareForBuild">
    <Error Text="This version of WinUI does not support $(_WinUIPlatformTarget). Either set Platform or PlatformTarget to one of the following: x86, x64, or arm64." />
  </Target>
```
The condition should be updated to exclude library:
`Condition="'$(_WinUIPlatformTarget)' == 'ARM' or '$(_WinUIPlatformTarget)'=='AnyCPU' AND '$(OutputType)'!='Library' "`

Otherwise this is a showstopper for .NET components.

**Expected behavior**
Compiles just fine. AnyCPU only prevented for applications.

NuGet package version: 
0.8.0-preview and 0.8.0-rc

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

This is somewhat related to #893 but that one pertains to runtime support of apps, this is just compile time of components.

**Comment by dotMorten** [comment] 2021-06-17 22:13
I should have searched closed issues. Probably duplicate of this? https://github.com/microsoft/ProjectReunion/issues/922

**Comment by andrewleader** [comment] 2021-06-17 22:58
Closing as dupe of #922, and we've updated the milestone on that issue to 0.8 :)

**Comment by dotMorten** [comment] 2021-06-17 22:59
@andrewleader Thank you! Looking forward to GA

**Closed by andrewleader** 2021-06-17 22:58 UTC
Labels: bug

**Comment by gmurray81** [comment] 2021-06-18 16:14
I'm not sure how the duplicate actually fixes the issue. It isn't allowing compilation as AnyCPU, but rather removing AnyCPU from the project templates. Won't this just result in the AnyCPU solution platform just selecting _one_ of the platforms for the class libraries to build? Meanwhile @dotMorten's suggestion above restores the ability to build a class library as AnyCPU

**Comment by dotMorten** [comment] 2021-06-18 16:16
@gmurray81 My understand of that PR was that it was just a workaround until GA, but I probably be good to confirm

**Comment by gmurray81** [comment] 2021-06-18 16:18
I'm a bit non-plussed, because I'm trying to update to .8 and build our class libraries and nugets. But if I have to generate all the platforms individually... that would mean a lot of structural changes to the nugets, and target files? Unless I were to try to generate the runtimes layout in the nuget manually, I guess?

**Comment by gmurray81** [comment] 2021-06-18 16:19
I guess the other solution is to hack the targets file in the meantime. I was trying to override the `ValidateWinUIPlatform` target to work around this in the projects, but was unsuccessful in this, I guess. Maybe something I'm not grokking with the order that the targets are imported in this scenario.

**Comment by andrewleader** [comment] 2021-06-18 16:26
Hey @huichen123, can you clarify whether in 0.8 GA, class libraries will be able to build for AnyCPU rather than having to build all the platforms individually?

**Comment by huichen123** [comment] 2021-06-18 16:46
In 0.8GA, class library will build for AnyCPU.

**Comment by gmurray81** [comment] 2021-06-18 16:47
@huichen123 is there a different fix other than #925 ?
Because doesn't that just remove AnyCPU from platforms? Would still require building each platform individually for a class library...

**Comment by huichen123** [comment] 2021-06-18 16:53
@gmurray81 that change was supposed to be a quick workaround for 0.8-rc, and was abandoned. There are different fixes in internal repo for 0.8 GA.

**Comment by gmurray81** [comment] 2021-06-18 16:58
got it, thanks @huichen123
In the interim, is there a good work around to get it to actually build as AnyCPU?

**Comment by huichen123** [comment] 2021-06-18 17:13
If you are willing to modify your local nuget cache and you are using 0.8-preview or 0.8-rc, you can remove the reference to Microsoft.ProjectReunion.Bootstrap.dll in Microsoft.ProjectReunion.Bootstrap.targets in Microsoft.ProjectReunion.Foundation package. In addition, remove the check of AnyCPU in ValidateWinUIPlatform task in Microsoft.WinUI.targets in Microsoft.ProjectReunion.WinUI package.

**Comment by gmurray81** [comment] 2021-06-18 17:30
@huichen123 would you happen to know if there is a good way to just override those targets in the csproj files or another targets file? I haven't been successful at this... I have to assume it could be because the Reunion targets are getting implicitly added after mine maybe?

**Comment by huichen123** [comment] 2021-06-18 17:56
for sdk style project, you may check this out for overriding. https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019.

**Comment by dotMorten** [comment] 2021-06-18 19:17
>  would you happen to know if there is a good way to just override those targets in the csproj files or another targets file? I haven't been successful at this...

AFAIK there is not (apart from perhaps overwriting it after the restore task has run). I manually edited mine by adding to the anycpu condition that it `OutputType` can't be a `Library`, but does mean I won't be adding this to my CI build, and will be waiting for 0.8GA until I check anything in.

**Comment by gmurray81** [comment] 2021-06-18 19:32
```xml
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  
  <Target Name="ValidateWinUIPlatform"></Target>
  <Target Name="BinPlaceBootstrapDll"></Target>
```

This appears to work. Not sure if there are any side effects to making the sdk import explicit though.
