### ISSUE TITLE
Simple app with color picker leads to crash with Project Reunion preview release

### ISSUE THREAD

**Issue by syncsiva** [microsoft/ProjectReunion#599] opened 2021-03-18 04:36 UTC
**Describe the bug**
Simple app with color picker leads to crash with ProjectReunion in UWP and Desktop. Same works fine with WinUI3 Preview4.

**Steps to reproduce the bug**
[colorpicker-projectreunion.zip](https://github.com/microsoft/ProjectReunion/files/6161318/colorpicker-projectreunion.zip)

1. Run the attached sample it will leads to exception.

**Expected behavior**
App should run without any exception.

**Version Info**
<PackageReference Include="Microsoft.ProjectReunion">
    <Version>0.5.0-prerelease</Version>
</PackageReference>

NuGet package version: 
<PackageReference Include="Microsoft.ProjectReunion">
    <Version>0.5.0-prerelease</Version>
</PackageReference>

**Additional context**
Using flaggable enum in XAML leads to crash in ProjectReunion in our custom control. To check the same in color picker which has `ColorSpectrumComponents ` flaggable enum property.  But it leads to exception when not setting this property also. 

Code:

`
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
    <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    <ColorPicker x:Name="myColorPicker"/>
</StackPanel>
`

https://github.com/microsoft/microsoft-ui-xaml/issues/4562

**Comment by riverar** [comment] 2021-03-18 07:09
Can't reproduce. What build of Windows 10? Can you paste the stacktrace?

**Comment by syncsiva** [comment] 2021-03-18 10:35
@riverar  I'm using the same version.
![image](https://user-images.githubusercontent.com/18731572/111612726-c36e5780-8803-11eb-800a-d02939343784.png)

**Comment by riverar** [comment] 2021-03-18 16:09
Thanks, can repro on Windows 10 1909 18363. Upgrading Windows should resolve the issue but Project Reunion members are required to support downlevel to Windows 10 17763 so looks like a bug.

```
00 KERNELBASE!RaiseException
01 mrmcorer!Microsoft::Resources::ReportFatalException_AppIssue
02 mrmcorer!Microsoft::Resources::HandleFatalError
03 mrmcorer!Microsoft::Resources::Runtime::CResourceManagerInternal::_LoadCurrentDependentPackages
04 mrmcorer!Microsoft::Resources::Runtime::CResourceManagerInternal::InitializeWithProfile
05 mrmcorer!Microsoft::Resources::Runtime::CResourceManagerInternal::InitializeForCurrentApplication
06 mrmcorer!Microsoft::Resources::Runtime::CResourceManagerInternal::s_CreatePackageDefaultResourceManagerInternal
07 mrmcorer!Microsoft::Resources::Runtime::CResourceManagerInternal::s_GetPackageDefaultResourceManagerInternal
08 mrmcorer!Windows::ApplicationModel::Resources::Core::CResourceManagerFactory::get_Current
```

microsoft/microsoft-ui-xaml#4499 looks related. `ERROR_MRM_MAP_NOT_FOUND` on load of ProjectReunion PRI (e.g.  C:\Program Files\windowsapps\microsoft.projectreunion.0.5-prerelease_0.52103.9000.0_x86__8wekyb3d8bbwe\resources.pri)

**Comment by riverar** [comment] 2021-03-18 16:51
ping @StephenLPeters

**Comment by axelandrejs** [comment] 2021-03-24 20:36
This will be fixed in the next drop of 0.5

**Closed by axelandrejs** 2021-03-24 20:36 UTC
Labels: area-Resources, bug

**Comment by riverar** [comment] 2021-03-24 21:18
@axelandrejs Is there a commit in this repository that corresponds to a fix for this issue?

**Comment by axelandrejs** [comment] 2021-03-24 21:49
@riverar sadly not, this was fixed by something ingested into this project. I sadly can't point you to a commit.

**Comment by riverar** [comment] 2021-03-24 23:29
Guess that means this is fixed in WinUI 3 and you can't point me to a commit because it's not open to the public yet.

@andrewleader this secretive WinUI release schedule will impact your channel proposal, just a heads up. At least until WinUI 3 code is available (sometime in the far future).

**Comment by mrlacey** [comment] 2021-03-25 10:23
> @riverar sadly not, this was fixed by something ingested into this project. I sadly can't point you to a commit.

Can issues that are closed this way be labeled (or added to a project, or milestone) that makes it clear which release this will be in?
Not only would this enable accountability, it would also make it possible to easily verify that things are intended to work do and so duplicates or regressions aren't raised incorrectly.
