### ISSUE TITLE
Improved crash experience for all apps

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#349] opened 2020-12-27 08:42 UTC
# Proposal: Improved crash experience for UWP apps
Today when an unhandled exception is reached to the UI thread, it hangs for some time and goes away. In desktop apps however, it tells that it's reporting the issue to Microsoft but in UWP apps it does report but without telling the user. Both of these are frustrating and is not a good experience.

## Summary
When an exception is thrown and no debugger is there and it doesn't get caught, I simply expect the app window to become invisible and hidden from the taskbar instantly and the report operation + stack unwinding should continue in the background without the user noticing. A notification could be sent that Windows is sending a report instead of a blocking dialogue box.
This will make more sense and make Windows less frustrating to use at times.

## Rationale

* Make Windows better to use
* Less time spent on displaying dialog box allowing the user to do other stuff

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to use their PCs without apps hanging because of crash | Must |

**Comment by Jaiganeshkumaran** [comment] 2020-12-27 08:55
This may not work well with desktop apps since they create the window on their own with CreateWindow function however since UWP app windows are owned by the system when it detects an unhandled exception, it should just hide the window without terminating the app process

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 03:36
Is it possible for Windows to retrieve the last non-successful HRESULT's message that can be sent as a notification so the user knows what caused the problem. Many apps handle UnhandledException in the App class but often have issues.

**Comment by VagueGit** [comment] 2021-01-07 06:02
We log exceptions to the App Center. On UnhandledException we log the exception and and try to pop a ContentDialog to let the user know we are tracking the issue.

The ContentDialog won't always show. Of course if the issue is memory exhaustion or something like that, there is not much can be done. Still it would be nice to have something light-weight that will fly when ContentDialog wont.

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 06:05
@VagueGit Although a ContentDialog could be useful for some errors, you shouldn't show it for everything. If critical exceptions occur, you should just terminate.

**Comment by BenJKuhn** [comment] 2021-01-13 01:00
Unfortunately, this isn't an issue that can be addressed in Project Reunion. Not all OS functionality fits the model, and in this case, application crashes are squarely in the domain of the core OS code. I've forwarded this to the appropriate OS team to investigate further.

Thanks,

Ben

_For reference of the Windows Development Team, this is OS work item ID: 31335662. Note that the OS work database is not public. The information is included here only for cross-referencing purposes by the OS development team._

**Closed by BenJKuhn** 2021-01-13 01:00 UTC
Labels: feature proposal

**Comment by Jaiganeshkumaran** [comment] 2021-02-27 03:51
Many services today exist for crash reporting however they can't send exception that can't be easily caught. It would be nice if Windows could send the crash report to a custom server specified in the manifest
