### ISSUE TITLE
App execution alias doesn't work for packages containing a UWP Console app

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#455] opened 2021-02-18 08:30 UTC
**Describe the bug**

Today app execution alias doesn't work for UWP console apps (not full trust console app) as Windows thinks it's a UI app and shows a splash screen waiting for activation but that never happens in a console app.

**Steps to reproduce the bug**

1. Install UWP Console app project templates for Visual Studio Marketplace
2. Create a new UWP console app
3. Add app execution alias to manifest
4. Deploy the application
5. Try to use the command specified in the manifest from the Run box
6. See the problem

**Expected behavior**

It should launch the UWP console app correctly. It works for Win32 console apps fine but not for UWP console apps.

**Comment by andreww-msft** [comment] 2021-02-19 21:25
Thanks for your feedback. I've tried to repro the issue, but it all actually works as expected for me. I've tried with VS2019 as well as with the VS2019 preview, without any problems.  Can you clarify one point: at step 3 you say you're adding an app execution alias - but the console template creates an alias for you. Are you adding a second alias? If so, are you declaring multiple aliases or multiple alias extensions? Also, which language are you using (C#, C++/CX or C++/WinRT)? Finally, when you build the project, can you confirm whether or not the alias shows up in %LOCALAPPDATA%\Microsoft\WindowsApps?

**Comment by riverar** [comment] 2021-02-19 22:11
Just throwing out there, I can't reproduce either.

My steps were:
1. Create Console App C# (Universal Windows) project named `Issue455Repro`
2. Deploy application out of the box
3. Start > Run > `Issue455Repro.exe arg1 arg2 arg3`
4. Observe app starts and prints arguments

Windows 10 19042.804, Visual Studio 2019 16.8.5

**Comment by andrewleader** [comment] 2021-02-22 20:15
Closing this as no-repro, but feel free to discuss further!

**Closed by andrewleader** 2021-02-22 20:15 UTC
Labels: area-Platform, needs-triage :mag:
