### ISSUE TITLE
[User32] Handling WM_NCCREATE clears window text

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/ProjectReunion#482] opened 2021-02-25 21:34 UTC
**Describe the bug**
When handling the `WM_NCCREATE` message, the application window looses its set text.

**Steps to reproduce the bug**
1. Create a new Windows Desktop Application in visual studio
2. Add `case WM_NCCREATE:
        return 1;` to the `WndProc` function.
3. Build and run the solution
4. Notice how the window looses its text

**Expected behavior**
The window should keep its text, it should not be cleared.

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |

**Comment by andrewleader** [comment] 2021-03-01 21:04
Thanks for reporting this! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31909365) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!

**Closed by andrewleader** 2021-03-01 21:04 UTC
Labels: area-Platform

**Comment by AzAgarampur** [comment] 2021-03-01 21:31
Thank you. Is there a designated place I can report platform bugs in the future?

**Comment by andrewleader** [comment] 2021-03-01 21:33
To be honest, not really. Your best bet right now would be to submit an issue here similar to what you did, and then we'll ensure it's tracked internally.

Hopefully we can improve that in the future.

**Comment by rkarman** [comment] 2021-03-01 21:36
This is not a bug, it is behaving exactly as expected. 😃 

If you want to listen to, and do updates during, the creation of the non client area you must do (some of) the work that comes with it. For getting the default titlebar properly setup while handling WM_NCCREATE, please modify your case statement so that you call the DefWindowProc and return it's return value. You can do that by NOT returning or breaking in the WM_NCCREATE case, and instead letting the case statement flow through to default:, or you can explicitly call the DefWindowProc and return it's value:
    case WM_NCCREATE:
    {
        return DefWindowProc(hWnd, message, wParam, lParam);
    }
