### ISSUE TITLE
Crash occurs while using CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/ProjectReunion#602] opened 2021-03-18 08:25 UTC
**Describe the bug**
Crash occurs while using CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture. Please refer the below code examples:

public MainPage()
 {
        this.InitializeComponent();
         string name = CultureInfo.CurrentUICulture.Name;
 }

**Steps to reproduce the bug**
1. Run the sample.

**Expected behavior**
Application crashes while using CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture.

**Version Info**

6.2.12
0.5.0-prerelease

**Sample:**
[WINUI-sample.zip](https://github.com/microsoft/ProjectReunion/files/6162372/WINUI-sample.zip)

**Note:**
Comment out **string name = CultureInfo.CurrentUICulture.Name;** in application, then application run without any crash.

**Comment by riverar** [comment] 2021-03-18 08:31
![Screenshot of "en-us" value stored in name variable as expected](https://user-images.githubusercontent.com/475132/111595438-5c13c180-8789-11eb-96a4-a31ec04eaf92.png)

Can't reproduce with Visual Studio 16.10.0 Preview 1.0 and your attached solution.

What does `6.2.12` refer to under Version Info? Can you provide more information on the crash? Stacktrace? Screenshot?

**Comment by mageshsankar** [comment] 2021-03-18 09:04
Hi @riverar,

I have meant Microsoft.NETCore.UniversalWindowsPlatform package version as 6.2.12. Please find the screenshot regarding it below:
![image](https://user-images.githubusercontent.com/55440472/111598844-a3d03280-87f5-11eb-8ef1-e5a5af91d461.png)

Also, i am using Visual Studio 16.10.0 Preview 1.0 still i am facing crash when using CultureInfo.CurrentCulture, CultureInfo.CurrentUICulture in application:
![image](https://user-images.githubusercontent.com/55440472/111599072-e6920a80-87f5-11eb-89b4-ae08582c623a.png)

It does not shows any stack trace details. Please find the screenshot regarding the crash below:
![image](https://user-images.githubusercontent.com/55440472/111599583-70da6e80-87f6-11eb-86f2-dc513432ec01.png)

Suppose, if we modify the ApplicationProcess of Debbugger type as Mixed in Debug properties of application, then crash occurs in Kernel base dll. Please find the screenshot regarding it below
![image](https://user-images.githubusercontent.com/55440472/111599994-ee9e7a00-87f6-11eb-82d0-fb353b871c51.png)

![image](https://user-images.githubusercontent.com/55440472/111600137-17267400-87f7-11eb-9942-27f9c63a3307.png)

**Comment by riverar** [comment] 2021-03-18 17:13
Dupe of #599, same stack.

**Comment by andrewleader** [comment] 2021-03-18 19:30
Closing as dupe of #599 (these are all related to resource loading issues on Windows 10 18363 and lower).

**Closed by andrewleader** 2021-03-18 19:30 UTC
Labels: needs-triage :mag:
