### ISSUE TITLE
Crash while creating Regex.

### ISSUE THREAD

**Issue by SenthilKumaranRajan** [microsoft/ProjectReunion#603] opened 2021-03-18 11:02 UTC
Crash While creating Regex.

string validator;
Regex regex;
public MainPage()
{
   this.InitializeComponent();
   validator = "^[a-zA-Z0-9_]*$";
    regex = new Regex(validator);
}

**Comment by andrewleader** [comment] 2021-03-18 19:25
Closing as dupe of #599 (these are all related to resource loading issues on Windows 10 18363 and lower and tracking with 599).

**Closed by andrewleader** 2021-03-18 19:25 UTC
Labels: needs-triage :mag:
