### ISSUE TITLE
Cannot start process despite it being present on system. Works in .NET Core 5.0

### ISSUE THREAD

**Issue by ivberg** [microsoft/ProjectReunion#898] opened 2021-06-01 21:28 UTC
**Describe the bug**
Starting a process is broken in Reunion app despite the app running in full trust and as Admin.

You will get this exception despite the file being present and the EXACT same code working in a .NE Core 5.0 app

System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified.
  Source=System.Diagnostics.Process
  StackTrace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs:line 618

**Steps to reproduce the bug**

1. Produce a C# Reunion 0.5 OR Reunion 0.8 Preview app
2. Modify app.manifest
--app.manifest--
`
\ <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
     <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator"/>
      </requestedPrivileges>
    </security>
  </trustInfo>  \
`
3. For MSIX package modify capabilities to allow Elevation
`
 \ <Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <rescap:Capability Name="allowElevation" />
  </Capabilities>  \
`

Run this code or similar (wpr.exe is a system process under System32 (C:\Windows\System32\wpr.exe)
This program requires admin privileges BTW
`
            var pStartInfo = new ProcessStartInfo();
            pStartInfo.FileName = @"wpr.exe";
            pStartInfo.Arguments = "-start GeneralProfile";
            pStartInfo.UseShellExecute = false;

            Process.Start(pStartInfo);
`

**Expected behavior**
Process launches w/o error the same as on console app

**Screenshots**

**Version Info**

Reunion 0.5 OR Reunion 0.8 Preview app
`
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7" />
`

OR
`
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21996)              | Yes   |
| May 2020 Update (19041)            |  ?  |
| November 2019 Update (18363)       | ? |
| May 2019 Update (18362)            | ?  |
| October 2018 Update (17763)        | ? |

**Additional context**

**Comment by riverar** [comment] 2021-06-01 22:11
@andrewleader Project Reunion apps still don't support elevation, right?

**Comment by andrewleader** [comment] 2021-06-02 16:59
Hi @ivberg, I couldn't reproduce this problem. **Does the exception get thrown when calling `Process.Start(pStartInfo);`? And you've confirmed the app runs normally if you comment out that code?** It works for me (briefly shows the command prompt), and it works even if I don't run the app elevated (and works if running elevated too).

@riverar some of the latest Insider builds might support elevation (it requires an OS-level change). I'm not sure if or which Insider build added that support.

**Comment by ivberg** [comment] 2021-06-02 17:28
Thx for trying to reproduce @andrewleader. Odd that it doesn't repro for you. Yes the exception is on `Process.Start(pStartInfo);`

As the bug says, I am on a pretty new CO build - 21996. Do you know which build added the support?

P.S. The process will start no matter if you are elevated or not, it's just that it won't actually work unless elevated.

**Comment by andrewleader** [comment] 2021-06-02 18:28
It's looking like this isn't related to Project Reunion, possibly a bug related to MSIX or something else. We are investigating this on an email thread, but closing this item as it's not a Project Reunion bug.

**Closed by andrewleader** 2021-06-02 18:28 UTC
Labels: needs-author-feedback
