### ISSUE TITLE
Question: When will filesystem access be added

### ISSUE THREAD

**Issue by ZodmanPerth** [microsoft/ProjectReunion#150] opened 2020-08-24 06:36 UTC
Accessing the filesystem from UWP using the UWP APIs is incredibly slow, and the API is very difficult to use.  Difficult APIs can be overcome, but the painfully slow API cannot.  Please see [this discussion on microsoft-ui-xaml](https://github.com/microsoft/microsoft-ui-xaml/issues/1465) for a lot of context.

It would be a tremendous benefit to UWP if ProjectReunion prioritised filesystem access to be added ASAP if access speeds were an improvement over the UWP API (a very low bar).  As someone writing an in-app file explorer in UWP, I would be very interested in trialing it.

I can't see any mention of filesystem in the roadmap.  Has it's inclusion been discussed yet?

**Comment by jonwis** [comment] 2020-08-24 07:20
This looks like a duplicate of #8 and maybe #88  - can you pile any additional comments or thoughts over there?

We don't have a timeline for it, but we're very aware of the problems and hope to have more information soon.

Until then, you could consider using the `...FromApp` APIs that might speed up things like enumeration and IO. Might not meet your use cases for a full filesystem browser, so please leave any additional requirements in either of those issues.

**Closed by jonwis** 2020-08-24 07:20 UTC
Labels: needs-triage :mag:, question

**Comment by ZodmanPerth** [comment] 2020-08-25 01:37
I agree this is a duplicate.  Strangely nothing showed up in search before I created this issue.

Thanks for the guidance.

**Comment by soumyamahunt** [comment] 2020-08-25 14:50
@jonwis is there any `...FromApp` method for renaming files. `StorageFile.RenameAsync` only allows reaming to file type that are declared in manifest, also doesn't support renaming if file was dragged to the app??

**Comment by jonwis** [comment] 2020-08-26 01:28
How about https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846627(v=vs.85) ? On Windows, rename is usually modeled as move-to-new-name.

**Comment by soumyamahunt** [comment] 2020-08-26 04:14
> How about https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846627(v=vs.85) ? On Windows, rename is usually modeled as move-to-new-name.

Does this require access to the root folder?? The app I am trying to implement it on will not have any `broadFileSystemAccess`, so app will only have access to the file that has been opened by the app. I am getting "Access Denied" when trying to use this method.
