### ISSUE TITLE
Using RegEx leads to crash

### ISSUE THREAD

**Issue by syncsiva** [microsoft/ProjectReunion#604] opened 2021-03-18 11:39 UTC
**Using RegEx leads to crash in Project Reunion and same works fine with WinUI3 Project templates**

Sample:
[RegEx issue.zip](https://github.com/microsoft/ProjectReunion/files/6163677/RegEx.issue.zip)

Visual Studio Version: 19.10 Preview 1.0
Windows Version: 
![image](https://user-images.githubusercontent.com/18731572/111622132-d175a580-880e-11eb-9f33-bf6852d7f4c6.png)

**Update:** The same works fine with Microsoft Windows Version 20H2

1. run the sample and click the button where simple regex condition code added.
2. once clicked the button app crashed with below error
![image](https://user-images.githubusercontent.com/18731572/111620404-ad18c980-880c-11eb-9119-2e638b2fd1dd.png)

Note: The same code works fine with WinUI3 Preview4 and not working with Project Reunion.

**Comment by riverar** [comment] 2021-03-18 17:08
Dupe of #599, same stack.

**Comment by andrewleader** [comment] 2021-03-18 19:23
Closing as dupe of #599

**Closed by andrewleader** 2021-03-18 19:23 UTC
Labels: needs-triage :mag:
